/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftMarketPlaceErc1155Sol from "./NFTMarketPlaceERC1155.sol";
export type { nftMarketPlaceErc1155Sol };
export type { NFTMarketplace } from "./NFTMarketplace";
