/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { NFTMarketplaceErc115 } from "./NFTMarketplaceErc115";
