/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { NFTMarketplaceErc1155 } from "./NFTMarketplaceErc1155";
