/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nftMarketPlaceErc1155Sol from "./NFTMarketPlaceERC1155.sol";
export { NFTMarketplace__factory } from "./NFTMarketplace__factory";
