/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155TokenReceiver__factory } from "./ERC1155TokenReceiver__factory";
export { NFTMarketplaceErc115__factory } from "./NFTMarketplaceErc115__factory";
