/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155TokenReceiver__factory } from "./ERC1155TokenReceiver__factory";
export { NFTMarketplaceErc1155__factory } from "./NFTMarketplaceErc1155__factory";
